### ISSUE TITLE
Add @reboot entry to cron so LiveLog resumes immediately on startup

### ISSUE THREAD

**Issue by finlayedridge** [trastle/rpi-weather#7]
With current instructions, after Raspberry Pi starts up, the LiveLog will resume (and re-check that it's running) at 25 or 55 mins past the hour. Would be great if it could run immediately at machine startup too, which it will if you add this line to the cron setup:

@reboot /home/pi/weather/scripts/pywws-live.py

**Comment by trastle** [comment]
Thanks Fin.
Fixed.
